export const stockData = [
  {
    id: "stock-1",
    symbol: "NIKE",
    name: "Nike",
    price: "₹1300.45",
    change: "-15.67",
    percentage: "(-1.19%)",
    changeClass: "text-orange-600",
    photo: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg",
  },
  {
    id: "stock-2",
    symbol: "BMW",
    name: "BMW",
    price: "₹1800.34",
    change: "+50.67",
    percentage: "(2.89%)",
    changeClass: "text-green-600",
    photo: "https://upload.wikimedia.org/wikipedia/commons/4/44/BMW.svg",
  },
  {
    id: "stock-3",
    symbol: "SAMS",
    name: "Samsung",
    price: "₹980.67",
    change: "+8.23",
    percentage: "(0.84%)",
    changeClass: "text-green-600",
    photo: "https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg",
  },
  {
    id: "stock-4",
    symbol: "AAPL",
    name: "Apple",
    price: "₹150.34",
    change: "+3.56",
    percentage: "(2.42%)",
    changeClass: "text-green-600",
    photo: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
  },
  {
    id: "stock-5",
    symbol: "MSFT",
    name: "Microsoft",
    price: "₹310.45",
    change: "+5.12",
    percentage: "(1.67%)",
    changeClass: "text-green-600",
    photo: "https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg",
  },
  {
    id: "stock-6",
    symbol: "AMZN",
    name: "Amazon",
    price: "₹3500.99",
    change: "-10.23",
    percentage: "(-0.29%)",
    changeClass: "text-orange-600",
    photo: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
  },
  {
    id: "stock-7",
    symbol: "TSLA",
    name: "Tesla",
    price: "₹720.88",
    change: "+22.56",
    percentage: "(3.23%)",
    changeClass: "text-green-600",
    photo: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Tesla_logo.png",
  },
  {
    id: "stock-8",
    symbol: "NFLX",
    name: "Netflix",
    price: "₹1450.45",
    change: "+10.23",
    percentage: "(0.71%)",
    changeClass: "text-green-600",
    photo: "https://upload.wikimedia.org/wikipedia/commons/6/69/Netflix_logo.svg",
  },
  {
    id: "stock-9",
    symbol: "META",
    name: "Meta",
    price: "₹2600.22",
    change: "-12.33",
    percentage: "(-0.47%)",
    changeClass: "text-orange-600",
    photo: "https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg", // Meta logo
  },
  {
    id: "stock-10",
    symbol: "GOOGL",
    name: "Alphabet",
    price: "₹2800.12",
    change: "+15.23",
    percentage: "(0.54%)",
    changeClass: "text-green-600",
    photo: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg", // Google logo
  },
];
